--- #YAML:1.0
name:               Win32-LockWorkStation
version:            0.01
abstract:           Win32 Lock Workstation
author:
    - Michael Vincent <vin at vinsworld dot com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Simple:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
